[package]
name = "good-turing"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy-regex = "3.1.0"
wasm-bindgen = "0.2.93"

[dev-dependencies]
wasm-bindgen-test = "0.3.43"

[lib]
crate-type = ["cdylib", "rlib"]
